import { Button } from '@material-ui/core';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const Container = styled.div`
  background: #333;
  display: flex;
  align-items: center;
  justify-content: space-between;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Container>
        <div>
          <h1>Venda mais com a tree pay</h1>
          <Button variant="contained" color='secondary'>Contained</Button>
        </div>
        <Image src='/design.svg' alt='ilustration' width={400} height={200}/>
      </Container>
    </>

    
  )
}

export default Home
